apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: ${CLICKHOUSE_USER}
      defaultDatabase: ${CLICKHOUSE_DB}
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
